### ISSUE TITLE
Error blocking users from being able to get to their order page to pay

### ISSUE THREAD

**Issue by jpitts** [esPass/pretix-eth-payment-plugin#76] opened 2019-07-19 23:52 UTC
I cannot paste the error info here as it contains user-revealing info. However this error affects several users.

> KeyError at ..URL..  
> 'currency_type'
> 

Zendesk Case: 4525

Rollbar: https://rollbar.com/ethereum/Devcon5-pretix-Production/items/4/

**Comment by davesque** [comment] 2019-07-20 00:11
Duplicate of #68.  Issue was fix in #73.

**Closed** 2019-07-20 00:11 UTC
